### ISSUE TITLE
(3.0.53) remove class in hierarchy class view does not work

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#377]
Before:
![image](https://user-images.githubusercontent.com/623951/50493430-46f8bf80-09d2-11e9-97be-0212036d693f.png)
After (no error or other notification):
![image](https://user-images.githubusercontent.com/623951/50493453-727baa00-09d2-11e9-953c-a83ea3b6744f.png)
...works when not in hierarchy mode

**Comment by LisaAlmarode** [comment]
It does remove the class, it just doesn't update the view, so the class appears to be there.  Since it's showing the methods still and if you try to edit the method you get a walkback... it gets messy.

**Comment by LisaAlmarode** [comment]
I've reproduced what is probably the real issue here.  

Class operations in hierarchy view are simply ignored if no class was selected in class view

To reproduce:
In one package select a class.  Change to hierarchy view.
Then select a different package, so you are in a hierarchy view with no class selected.
Click on a class to select it.  Try variously the remove and the add subclass menu items.  
See nothing happen.

This issue covers two separate sub-cases for removing a class in hierarchy view: 
  (1) with class selected, remove occurs but does not update view 
  (2) without class selected, no remove occurs and other things also don't occur.

**Comment by ericwinger** [comment]
Hierarchy view was broken. The only reason the class was removed in (1) was because it happened to be selected in the class list. Should be fixed in 3.0.57. https://github.com/GemTalk/Jadeite/commit/9eadcdc36338d64497885288919530ff6d3e4b55

**Comment by LisaAlmarode** [comment]
Other class menu items now work in hierarchy view, but add subclass is still a no-op or even adds a subclass to the wrong class.

In class list view, select a class and go to hierarchy view.
Select a superclass or subclass of the selected class.
add subclass displays the definition to create a subclass on the class that was selected previously in the class list view, NOT the class that is currently displayed as selected...

If nothing was selected before looking at the class heirachcy, add subclass is a no-op.

**Comment by LisaAlmarode** [comment]
The part of this bug that wasn't fixed is now in #422, so reclosing.
