### ISSUE TITLE
Fix for cross-browser clearing test results is incomplete in 3.0.60

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#432]
Fixes have been made in the clearing of test results between browsers per issue #419 and issue #293.  Closing both those per Eric's request and opening a new issue.  
Marking as February since this is really part of one of the stability issues that was intended to be fixed for this drop.

Specific known problems:

- [x] Have two project browsers open on two different test classes.  No other browsers open on any of these classes.
In one, go to the sunit tab and run tests.  See icons.
In the other, select the same class that is selected in the first browser.  See test icons disappear.

- [x] Have two project browsers open on the same test class.  No other browsers open on this class. 
In one, go to the sunit tab and run tests.  See icons.
In the other, edit a method (it's more compelling when you edit a method that isn't a test method, but it doesn't matter).  See test icons disappear.

These operations don't effect the Sunit browser.  If you have the Sunit browser sitting around, these bugs don't show themselves, since the Sunit browser creates great stickiness of test results.

**Comment by ericwinger** [comment]
Should be a fix for part 1 in https://github.com/GemTalk/Jadeite/commit/28b45e1b40d213ddd8a1663c7cd9a3779c6c277d

**Comment by ericwinger** [comment]
I'm pretty sure that the second item was fixed as part of the first in 3.0.61. Please reopen if that is not so.

**Comment by LisaAlmarode** [comment]
still see some behavior that's not entirely solid when it comes to cross-browser sunit result; the banner is too quick to clear in the project browser and maybe not quick enough in the sunit browser, and I'm not sure the exact semantics of the browser in some cases.  However, it's no longer appears to be confusing, wrong or losing results, so I'll call it good enough.
