### ISSUE TITLE
Funny orange boxes enabled for Sunit tab, but error

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#556]
I saw some orange arrows and a red x on the upper right of my PB.  When I click on these I get error dialogs such as "JadeiteSUnitInClassPresenter does not understand #moveCardRight".

It appears that these boxes are disabled normally (correctly when I have just one project tab open), but become enabled when I click on the Sunit tab for a test class.

**Comment by ericwinger** [comment]
Fixed in 3.0.80.  Moving system tabs was broken but only when sunit tab was selected.

**Comment by LisaAlmarode** [comment]
The orange buttons still get enabled when I click on the Sunit tab (with only one project tab).  The left and right don't error, but they shouldn't be enabled at all.

The x closes the current tab, leaving no tabs at all in the browser, which is wrong-er.  However, this can be deferred for November.

**Comment by ericwinger** [comment]
Fixed in 3.0.84
