### ISSUE TITLE
Save in method list browser code pane

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#63]
In the Method List Browser lower code pane there's a popup menu.

the save menu item on this, gets an error: UndefinedObject does not understand #behavior.

Other options work fine

**Comment by ericwinger** [comment]
Fixed in 3.0.13. Not sure what the method list browser was trying to do, but it seems to work now ... and uses the same code paths as the projects browser (what a concept). 

Lots of refactoring in the method save & selection area. I may have perturbed something in the process. See commit comment for a few more details.

**Comment by LisaAlmarode** [comment]
I updated the content (not the selector) of a method in the jadeite method list browser. 
Save works and saves the method, good.

BUT the contents of the method in the method list browser still show the old, pre-saved method contents.  Not so good.

**Comment by ericwinger** [comment]
If I understand, here is the reproduction case: 

- Save method in method list browser. 
- Deselect method
- Reselect method
- See old source (even though new source saved) 

Fixed in 3.0.14

**Comment by LisaAlmarode** [comment]
reproduction case accurate and verified fixed in 3.0.14
