### ISSUE TITLE
(3.0.87) Opening workspace from Jadeite.prefs doesn't work on first login

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#632]
Customer reproduction case demonstrated. Subsequent logins, the workspace opens. 
Preferences line looks like this: 
`openWorkspace: i:\jadeite\00_workspace.gs`

Very odd. Need to reproduce in house.

**Comment by ericwinger** [comment]
Preferences file from customer 
```
autocommitEnabled: false

autocompleteEnabled: false

breakpointsEnabled: true

loggingEnabled: false

#openBrowserOnClass: <class name>

#openBrowserOnPackage: <package name>

#openBrowserOnProject: <project name>

#openSUnitBrowserOnPackage: <package name>

openWorkspace: i:\jadeite\00_workspace.gs

transcriptEnabled: false
```

**Comment by ericwinger** [comment]
No luck on reproduction yet. Possibly, it's a file on a network drive and dolphin/windows can't find it immediately after the .exe is opened. Asked customer for file's location.

**Comment by ericwinger** [comment]
Fixed in 3.0.88 

Searching for the workspace in ``File workingDirectory`` was not adequate. Instead, we want to look in the image directory for workspace files if a full path isn't specified. Jade code was setting the working directory after login so it worked on subsequent logins.

**Comment by LisaAlmarode** [comment]
The code is still not doing the correct thing, in v3.0.88.3 with respect to a second login.   Assuming the opening-workspace behavior should be the same for both the first and second login. 

To reproduce, I set up a windows shortcut that specified a different working directory than the executable file.  
```
executable: c:\gs\Oscar\
working dir: c:\gs\Oscar\operations
```
This test involves four files:
```
  c:\gs\Oscar\testws1.gs
  c:\gs\Oscar\operations\testws1.gs
  c:\gs\Oscar\testws3.gs
  c:\gs\Oscar\operations\testws4.gs
```
Note that testws1.gs has the same name but different contents in the different directories.

And preferences:

```
openWorkspace: testws1.gs
openWorkspace: testws3.gs
openWorkspace: testws4.gs
```

On the first login, it opens these three files:
```
  c:\gs\Oscar\operations\testws1.gs
  c:\gs\Oscar\testws3.gs
  c:\gs\Oscar\operations\testws4.gs
```

On the second login, it opens:
```
  c:\gs\Oscar\testws1.gs
  c:\gs\Oscar\testws3.gs
```

and reports an error in attempting to open:
``` 
 c:\gs\Oscar\operations\testws4.gs
```

I think the specific complaints is the equivalent of testws3.gs, which does fail to get found in 3.0.88.1 and does get opened in 3.0.88.3.  Also in 3.0.88.3it will use the preferences file in the executable directory for both first and second logins.  In 3.0.88.1, it used the preferences file in the working directory for the first login, and then used the one in the executable directory for subsequent logins.

**Comment by ericwinger** [comment]
Something to keep in mind is that the files must reside in the same directory as the image unless a full path is specified in the preferences file. I wouldn't expect the preferences file you provided to open them correctly because you're not specifying full paths for those files that aren't in the .exe directory. 

```
openWorkspace: testws1.gs
openWorkspace: testws3.gs
openWorkspace: testws4.gs
```

Note - because I found a bit of a problem with the working directory, I changed the preferences to look for the image directory - i.e. the executable file directory.

**Comment by LisaAlmarode** [comment]
I don't mind the specific behavior, as long as it does the same thing on the first and second logins.  

If a full path is required unless the file is in the executable directory, then it's opening the incorrect file (c:\gs\Oscar\operations\testws1.gs) on the first login; it should be opening c:\gs\Oscar\testws1.gs.

**Comment by ericwinger** [comment]
This was a good catch. Found another place where `workingDirectory` was being used instead of the `imageDirectory`.  We should be consistent in our usage now. 

Note if you specific `operations\testws1.gs` it will open a file in a directory relative to the image directory.

**Comment by LisaAlmarode** [comment]
I'm afraid there is no change in behavior between 88-v3 and 88; see detailed comment above.  It still does different things for the first and second logins.

**Comment by LisaAlmarode** [comment]
![image](https://user-images.githubusercontent.com/13142166/69209555-7a719a80-0b0c-11ea-9cd0-031debe67c81.png)

first login:

![image](https://user-images.githubusercontent.com/13142166/69209599-af7ded00-0b0c-11ea-894e-3a4964c60714.png)
second login:
![image](https://user-images.githubusercontent.com/13142166/69209684-02f03b00-0b0d-11ea-9039-3b1b448842b2.png)

**Comment by ericwinger** [comment]
@LisaAlmarode I'll need to see the prefs file you're using.

**Comment by LisaAlmarode** [comment]
It's described in the early comment:
```
openWorkspace: testws1.gs
openWorkspace: testws3.gs
openWorkspace: testws4.gs
```

**Comment by LisaAlmarode** [comment]
Filed a new issue for the different behavior on first and second logins.  Closing this issue, since the single issue for the customer is fixed.
