### ISSUE TITLE
Commit to Git leaves old SHA red

### ISSUE THREAD

**Issue by martinmcclure** [ericwinger/Jade#691]
Start with a clean load from Git. The project is listed in the console and projects browser with normal black font.
Make some code changes in a project. The project is now listed in the console and projects browser with black bold italic.
In the console, right-click on the project and select "Commit to Git", enter a commit message, and click OK. The commit is made, but the console still lists the old SHA, and the package is shown in console and browsers in red.

The workaround is to always do a load immediately after a commit, but that's rather disturbing.

**Comment by ericwinger** [comment]
Possibly an issue with DataCurator? 

@martinmcclure says he is changing `FileSystemGs_dev` project which is in the `UserGlobals` of `DataCurator`

**Comment by LisaAlmarode** [comment]
I'm not seeing this as DataCurator in 93-1, but maybe it's some other factor.

**Comment by ericwinger** [comment]
@martinmcclure I, too, am not seeing this behavior.  Do you have a test server that's exhibiting the problem which I could log into and try to reproduce in a Dolphin environment?

**Comment by martinmcclure** [comment]
Try the default stone on Hey. I've put FileSystemGs_dev on a new branch "Eric-testing" to which you can make silly commits to test this bug.

**Comment by ericwinger** [comment]
When Jadeite commits a project to git, the project service sends this code:
```
Rowan projectTools write writeProjectNamed: name.
Rowan projectTools commit
	commitProjectNamed: name
	message: message.
```
Then, Jadeite updates the project service and sends this code to retrieve the new sha: 
```
^(RwProject newNamed: name) loadedCommitId
```

It's a bit difficult to debug, as the user `DataCurator` doesn't have visibility to the Rowan structures, but it appears that the update is finding the prior sha. Jadeite logs confirm that the update immediately following the commit does not find the updated sha. In a non-error use case, the new sha is returned. 

Since you can load the new sha, the commit was successful. That implies no error is hidden. 

@dalehenrich - I believe this might be a Rowan bug. Or, something peculiar about Martin's setup. 
I can run this script in a workspace and see that the new sha is not the `loadedCommitId`

```
current sha: 2313925

Rowan projectTools write writeProjectNamed: 'FileSystemGs_dev'.
Rowan projectTools commit
	commitProjectNamed: 'FileSystemGs_dev'
	message: 'test commit'.

(Rowan projectNamed: 'FileSystemGs_dev') loadedCommitId '2313925'
```

Assigning to @dalehenrich  for input.

**Comment by dalehenrich** [comment]
@martinmcclure, you are using the v2 code and I assume that @ericwinger is looking at v1 code ... I have not gone through the process of converting the v2 Services code to use the v2 api, so it is not surprising at this point that there are discrepancies in behavior ... I happen to be in the process of converting the Services code to use the v2 api and expect to be complete by the end of the week (if not sooner) ... 

@martinmcclure if you want to get rid of the `red`, a load of the project after a commit **should** properly set the loadedCommitId ...

**Comment by LisaAlmarode** [comment]
Remove from December and retire, as probably an artifact of Martin's environment and possibly fixed by Dale's later changes. Note the december project is specifically for v1/customer env.

**Comment by martinmcclure** [comment]
Reopening, since I'm still seeing this with Jadeite 3.1.0 and the latest dkh-rowanCandidateV2.0, developing as SystemUser.

**Comment by dalehenrich** [comment]
What is the exact sequence of events leading from black to red? As I think about this I'm not sure that the `loaded SHA` is changed on write ... I seem to recall that this happens to me when I have done a command-line commit before doing the write ... of course, if we pick up the SHA after we've written to disk, we will immediately get skew again if we do another command line commit ... Personally, I do a diff to make sure that there aren't any changes that I've missed and then a load to clear the skew ... again, personally I almost always want to deal with skew myself rather than have the system automatically clear skew ... 

As I think a bit more about, this it might make sense to update the `loaded sha` if we prompt the user to ask whether they want the sha updated after doing a diff?

**Comment by martinmcclure** [comment]
The sequence is:
1) Start with the project **isDirty** false, **skew** false.
2) Add a method. Now **isDirty** is true, **skew** false.
3) "Commit to Git" in project browser. **isDirty** is now set to false, but **isSkew** is true and the package is shown in red.The **Loaded Sha** has _not_ been changed.

It seems like if you do a commit _through Jadeite_ it should move the **Loaded Sha** to what it just committed.

**Comment by dalehenrich** [comment]
I've created a Rowan bug (GemTalk/Rowan#622) that references this one to take a look at the `git commit` logic and make sure that we update the loaded commitId on `git commit`

**Comment by LisaAlmarode** [comment]
Martin's reproduction case reproduces in v3.2.12.

**Comment by dalehenrich** [comment]
@LisaAlmarode, let's chat about this some time ...

**Comment by LisaAlmarode** [comment]
Looking at the behavior again when considering issue #844, and this is really quite serious, After you commit you always want to be able to confirm what you did; and Jadeite is totally unhelpful; you have to go to disk and use git. 
Jadeite help says, when it's red, you should not write to disk... so you can no longer work...

Refresh does not help at all.  You can reload the entire project again, but that's not an ideal workaround.

**Comment by dalehenrich** [comment]
lets chat about this sooner rather than later :)

**Comment by LisaAlmarode** [comment]
Agreed upon behavior (other than details of the warning messages):

- If the on-disk state of the git repository is not dirty, and the recorded sha in the image matches the one on disk, proceed with the commit. 

- If the on-disk state of the git repository is dirty, but the recorded sha in the image matches the one on disk, put up a dialog saying:
 
"The on-disk state of the git repository is dirty.  This may be due to a previous project write without commit, or change to the repository outside Jadeite. It is recommended to check status on the git command line before committing"
[ cancel commit ]  **[ proceed with commit ]**

- if the recorded sha in the image does not matches the one on disk, put up a dialog saying:

"The most recently loaded sha differs from the sha of the git repository.  It is not 
recommended to commit; if you are aware of the issues, you may continue to write and commit your image changes."
**[ cancel commit ]**  [ proceed with commit ]

If the commit proceeds, either since it's safe or the user confirms commit, we update the loaded sha in the repository to the sha of the commit that just occurred.

**Comment by ericwinger** [comment]
Added appropriate warnings & actions based on the previous comment. Will need reasonable review.
