### ISSUE TITLE
removing instance variables from class definition (3.0.92)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#692]
Say you have a class with two instance variables, each with accessor methods, and you realize you just added them to test something or another, so you edit the class definition to remove those instance variables.

You get a methods failing recompile... only one; but we'll see.

![image](https://user-images.githubusercontent.com/13142166/73225033-2690bc80-4120-11ea-91d9-4eae76830505.png)

But now, if I attempt to remove this method using the menu item Remove Method (s) I get an error:

![image](https://user-images.githubusercontent.com/13142166/73225021-1aa4fa80-4120-11ea-8c96-eb948903f852.png)

So I cannot just remove the method.

I can edit the method to just return self.  But that seems like a silly extra step.  

And then, I have to go back and try to save the class definition AGAIN and repeat this entire process for EACH method with a reference.

I don't think this is critical for December but it's sure unattractive...

**Comment by ericwinger** [comment]
Fixed in Oscar 3.1.0 (dolphin port version)

**Comment by LisaAlmarode** [comment]
It does not walkback; but the need to re-run the method save for each method is still present.  File that as new issue #757.
