### ISSUE TITLE
Answer no to "Unsaved Changes" on logout, can result in browser open after logout and multiple sessions logged in (3.1)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#773]
Say you have three open method browsers with changes, and you close the console/logout, per issue 747. And autocommit is on.

The dialog says "Keep unsaved changes?'.  But if I answer  yes... logout still continues.  
Now the console is gone, I have three method browsers up and every time I touch any of them I get an error dialog:

![image](https://user-images.githubusercontent.com/13142166/79394509-84b58a80-7f2c-11ea-8cc7-36bc0a150433.png)

The login button was enabled, so I could also log in again; after that, the method browsers stopped doing the autocommit complaint, but I got another error on commit.  But at least I could close those browsers.

**Comment by ericwinger** [comment]
Fixed in 3.1.0pre-release5. Menu query wasn't checking for nil session.

**Comment by LisaAlmarode** [comment]
Still not working in ways that make sense.  I seem to have got orphan windows that stuck around after logout, and then, using this feature, I am able to get two logins from the same Jadeite which is also a no-no.

I think if you request to logout, and then answer yes to "keep unsaved changes", the logout sequence needs to be aborted.  Continuing with the logout is creating a number of holes that would need to be patched.

@dalehenrich, what exactly do you want to happen here?  Seems rather than "keep unsaved changes" you were really thinking about something like a dialog "save changes" or "discard changes".

**Comment by ericwinger** [comment]
Although it has a new name,  "keep unsaved changes" functionally hasn't changed and it's always been scoped for one window without knowledge of logout. We can certainly change that but it would be a behavior change. Do you want to do that for 3.1.0?

**Comment by LisaAlmarode** [comment]
I'm not entirely sure of the history of this set of issues, but it does seem like this particular gaping hole filled with snakes might not be new.  As such, it doesn't need to be fixed for 3.1.  Also I really did want Dale's input.

**Comment by dalehenrich** [comment]
@LisaAlmarode, the best way to get my feedback is to ping me on slack ... I get email for all of the github interactions and often I read each one in detail ... recently there has been an avalanche of github messages while have been deep into the rowanization of 3.6.0, so I haven't been diligent about reading all of the messages and it was just by luck that I noticed that you wanted my input ...I am diligent at looking at all of the slack messages ... 

> what exactly do you want to happen here? Seems rather than "keep unsaved changes" you were really thinking about something like a dialog "save changes" or "discard changes".

I am not going to be too picky about how the problem is solved, but I think my involvement here must be due to #746, where Jadeite can freeze during shutdown due to invalid session and the `save changes` dialog appears to be implicated ... is that why you are asking me `exactly what do you want to happen here`? ...

Ah, I see that you must be referring to #747 (which is closed?) ... I think I was asking that the window title for the unsaved window be listed in the `Save changes` dialog so that I could make an informed decision about exactly which window I will be saving the changes for ... 

When I explicitly close a window, the dialog makes sense, but when I logout there can be any number of windows including multiple workspace windows or method windows that could have unsaved changes ... obviously saving method changes can't really be done unless you have autocommit turned on --- but what happens if there are compile errors --- If I'm logging out I might be inclined to want the option to abort the logout (depending upon the window which has unsaved changes)  ... for the invalid session error (#746), I assume that it is meaningless to prompt for saving a method, so only workspaces should be saved (assuming that it is possible to save workspaces with an invalid session) .... and of course I'd still like to know the name of the workspace file that needs saving. Iif there is no file associated with workspace, then auto save also does not make sense, while aborting a logout would allow me to manually save the workspace to a file ...

... so I guess this is what I think:)

**Comment by LisaAlmarode** [comment]
thanks, dale, that's helpful.  I have filed issue #781 (which is not specific to logout), and added a new issue #782 to cleanly handle unsaved changes on logout.  I'm going to close this issue since while the current situation is still buggy, I don't think patching is a good use of time...
