### ISSUE TITLE
Stubborn sorting in the Sunit browser

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#775]
In the Sunit browser,if you have several classes selected, it sorts them by selector.  You can use the column header to sort by class. 

I'm trying to sort out which ones should pass or fail and so I sort by class, but EVERY TIME I select one of these classes in the project browser it resorts the list by selector.

**Comment by LisaAlmarode** [comment]
The sort also isn't the same - as I click between classes in the PB, the Sunit list of classes (with the same method selector) is in different order after each click.

**Comment by ericwinger** [comment]
Fixed in 3.1.0. Sort order by column now "sticky" after class change.

**Comment by LisaAlmarode** [comment]
still the same in PR5; possibly due to my particular use case, which involves inherited tests.

This is the before: 

![image](https://user-images.githubusercontent.com/13142166/79896854-bcee1a80-83bd-11ea-9b44-2a98cc064dea.png)

In the project browser, I select one of the classes that I have selected in the SUnit browser:

![image](https://user-images.githubusercontent.com/13142166/79896890-cb3c3680-83bd-11ea-8072-acfbd88eba06.png)

**Comment by ericwinger** [comment]
Should be fixed in pre-release6

**Comment by LisaAlmarode** [comment]
Not fixed. _(programmer's note. Technically, the issue was fixed. This is a variant of the problem.)_ If save a new test method on the parent class in the project browser, and then click on one of the selected child test classes, the list in SUnit browser now only lists methods in that class, not in the other three selected classes. 

The selected classes in the sunit browser
![image](https://user-images.githubusercontent.com/13142166/80163792-199f3000-858c-11ea-93f8-43a42b4738b6.png)

Add a new test.  Note that it does not show up in the list, which is also a bug.
![image](https://user-images.githubusercontent.com/13142166/80163823-33d90e00-858c-11ea-8e8e-1b3a9b6616fb.png)

But if I then select a class in the project browser, it does update, but does not respect the selection in the sunit browser.

![image](https://user-images.githubusercontent.com/13142166/80163833-3b001c00-858c-11ea-99e2-fe67a992ed25.png)

**Comment by ericwinger** [comment]
What is the hierarchy relationship between the classes given as example? `LisaSubTest` `LisaSubTestTwo` Is there a common parent?

**Comment by LisaAlmarode** [comment]
The parent class is LisaTest, the child class is LisaSubTest, and LisaSubTestTwo is another child class of LisaTest.  Parent=superclass child=subclass.  I believe this behavior is the same if the parent class is abstract or not, as long as the children inherit test methods.

**Comment by ericwinger** [comment]
Should be fixed in 3.1.0pre-release7.
